title: Colors
status: ready
context: {
  colors: [
    {
      name: $blue,
      value: "#0666b0"
    },
    {
      name: $red,
      value: "#d10a11"
    },
    {
      name: $orange,
      value: "#eb7805"
    },
    {
      name: $darkBlue,
      value: "#0d436c"
    },
    {
      name: $lightBlue,
      value: "#9bc2df"
    },
    {
      name: $yellow,
      value: "#fab900"
    },
    {
      name: $grey,
      value: "#333333"
    },
    {
      name: $darkGrey,
      value: "#4c4c4c"
    },
    {
      name: $midGrey,
      value: "#a5a5a5"
    },
    {
      name: $lightGrey,
      value: "#e9e9e9"
    },
    {
      name: $black,
      value: "#000000"
    },
    {
      name: $white,
      value: "#ffffff"
    },
    {
      name: $gradientBlue,
      value: "linear-gradient(0.25turn, #0677b0, #064db0)"
    },
    {
      name: $gradientYellow,
      value: "linear-gradient(0.25turn, #fab900, #fa9900)"
    },
  ]
}
